export const GET_CRYPTO_LIST = 'GET_CRYPTO_LIST';
export const PING_CRYPTO_LIST = 'PING_CRYPTO_LIST';
export const GET_CURRENT_CRYPTO = 'GET_CURRENT_CRYPTO';
export const GET_WATCH_LIST = 'GET_WATCH_LIST';
export const GET_ASSET_LIST = 'GET_ASSET_LIST';
